spring:
  application:
    name: infosec-lab1-dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pg-dev
    username: dev-username
    password: dev-password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

token:
  signing:
    key: YmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9sYmVia2VrbG9s
